[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
via_ir = true
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
avalanche = "https://api.avax.network/ext/bc/C/rpc"
avalanche_fuji = "https://api.avax-test.network/ext/bc/C/rpc"

[etherscan]
avalanche = { key = "${SNOWTRACE_API_KEY}", url = "https://api.snowtrace.io/api", chain = 43114 }
avalanche_fuji = { key = "${SNOWTRACE_API_KEY}", url = "https://api-testnet.snowtrace.io/api", chain = 43113 }